### ISSUE TITLE
Refactor integration.yml

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1758]
**What feature(s) would you like to see in RepoSense?**

Currently, the CI for each OS is defined separately (1 for ubuntu, 1 for macos, 1 for windows) while the steps for each of them tend to be similar.

**Is the feature request related to a problem?**

Such a setup violates the DRY principle and is difficult to maintain. In particular, when updating the `node-version`, it had to be done 4 times (1 for each OS and 1 more for cypress). The `node-version` update for cypress was actually missed and had to be added in a later PR.

There are 2 possible approaches I can think of:

**1) Merge the OS matrix, then make them share the same steps:**
```
name: ${{ matrix.os }} JDK 8
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11, windows-2022, windows-2019]
    runs-on: ${{ matrix.os }}
    env:
      NODE_VERSION: "lts/*"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
```
The code for macos and ubuntu are similar, but the code for windows may differ. A possible solution with Gradle caching as an example would be:
```
- name: Set up Gradle caching (Ubuntu and MacOS)
      uses: actions/cache@v2
      if: ${{ !(matrix.os == 'windows-2022' || matrix.os == 'windows-2019') }}
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ matrix.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ matrix.os }}-gradle-

- name: Set up Gradle caching (Windows)
      uses: actions/cache@v2
      if: ${{ matrix.os == 'windows-2022' || matrix.os == 'windows-2019' }}
      with:
        path: |
          $HOME/.gradle/caches
          $HOME/.gradle/wrapper
        key: ${{ matrix.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ matrix.os }}-gradle-
```
This is similar to what is being done for [AB3](https://github.com/se-edu/addressbook-level3/blob/master/.github/workflows/gradle.yml)

One potential problem is that there are unique environment variables for each OS, such as `HOMEBREW_NO_AUTO_UPDATE: 1` for MacOS.

**2) Use composite actions**

As described [here](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action). This may allow us to keep the OS name definitions (and environment variables) separate while sharing the same steps. It may even be extended to the Cypress CI.

**Comment by gerhean** [comment]
I don't really like the first approach, since in the future when we want to upgrade the Windows CI, we will have to change all the ` if: ${{ matrix.os == 'windows-2022' || matrix.os == 'windows-2019' }}` and so on.

**Comment by dcshzj** [comment]
> I don't really like the first approach, since in the future when we want to upgrade the Windows CI, we will have to change all the ` if: ${{ matrix.os == 'windows-2022' || matrix.os == 'windows-2019' }}` and so on. This is ultimately similar to changing the node versions for everything.

We can make use of `runner.os` to [specify Windows only](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context), so it should not be an issue.

**Comment by gerhean** [comment]
I am ok with that.

**Comment by gok99** [comment]
```
jobs:
  # Build and unit test
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Determine npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - name: Prettier Format Check
      run: npm run format-check
    - name: ESLint Check
      run: npm run lint
    - name: Build & Test
      run: npm run test
```
[This](https://github.com/actions/cache/blob/main/.github/workflows/workflow.yml) workflow has a general solution for node caching using `npm config get cache`. If gradle has similar functionality, perhaps something similar can be done.
