### ISSUE TITLE
Add/Document a GitHub Action to automate publishing of the report

### ISSUE THREAD

**Issue by tlylt** [reposense/RepoSense#1771]
**What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?**

Hi RepoSense devs,

I was looking through the UG, especially the section on deploying RepoSense report via GitHub Actions here: https://reposense.org/ug/withGithubActions.html

I thought the need to fork a repository in order to set up a RepoSense report can be quite complicated and intimidating for a new user. I decided to play around with the existing scripts in publish-reposense and make an MVP - [`reposense-action`](https://github.com/tlylt/reposense-action) to ease the process by eliminating the need to fork. So, just do:
- Specify the config files in the configs folder of the target repo.
- Create a reposense.yml with the following content in `.github/workflows/`:
```yaml
name: Deploy RepoSense report

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: tlylt/reposense-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

Other options are available and documented in the readme. To address the problem of existing GitHub pages being used for other purposes, I provided an alternative deployment service option `surge`.

Opening this issue to see if there's any interest from RepoSense to adopt the action (into the organization) or document it in your UG as a utility tool out there. Otherwise, I am happy to continue working on it on my own as well (at least as long as I am interested in the project :))
